Makefile

add host Makefile

---

controllers/profile.go
dtos/profile.go
models/profile.go
repository/profile.go
repository/users.go
routers/profile.go

feat: CRUD-profile-update

---

controllers/products.go
migrations/000021_insert_product_sizes_table.down.sql
migrations/000021_insert_product_sizes_table.up.sql
models/products.go
repository/products.go
routers/products.go

1. add func for method GET in table product_size

feat: add func method GET in table product_sizes

---

repository/products.go

1. add fix func for method GET in table product_sizes

feat: fix func method GET in table productSizes

---

controllers/profile.go
repository/profile.go
routers/profile.go

feat: CRUD-profile-delete

---

controllers/productVariant.go
models/productVariant.go
repository/productVariant.go

feat:add backend product variant

---

controllers/orderTypes.go
migrations/000022_insert_order_types_table.down.sql
migrations/000022_insert_order_types_table.up.sql
repository/orderTypes.go
routers/main.go
routers/orderTypes.go

new backend and dummy data for order type

new backend and dummy data for database order type

---

controllers/productOrderType.go
dtos/productOrderType.go
migrations/000023_insert_products_table.down.sql
migrations/000023_insert_products_table.up.sql
models/productOrderType.go
repository/productOrderType.go
routers/main.go
routers/productOrderType.go

- add crud operations, include create, read, update and delete for table product_order_type
- do testing and there is an issue in updating the data (due to violating foreign key)

feat: create CRUD for product_order_type table

---

controllers/profile.go
controllers/transactionStatus.go
migrations/000023_insert_transaction_status_table.down.sql
migrations/000023_insert_transaction_status_table.up.sql
models/transactionStatus.go
repository/transactionStatus.go
routers/main.go
routers/transactionStatus.go

feat: backend transaction-status

---

controllers/carts.go
dtos/carts.go
migrations/000015_create_carts_table.up.sql
migrations/000023_insert_products_table.down.sql
migrations/000024_insert_product_variants_table.down.sql
migrations/000024_insert_product_variants_table.up.sql
models/carts.go
repository/carts.go
routers/carts.go
routers/main.go
routers/transactionStatus.go

feat: backend carts

---

controllers/profile.go
go.mod
go.sum
models/profile.go
repository/profile.go
routers/profile.go

feat: get all profile

---

controllers/products.go
repository/products.go

feat: fix products pagination

---

migrations/000026_insert_promo_table.down.sql
migrations/000026_insert_promo_table.up.sql

feat:add insert promo

---

controllers/profile.go
repository/users.go

fix: update profile

---

controllers/products.go
migrations/000026_insert_product_images_table.down.sql
migrations/000026_insert_product_images_table.up.sql
models/products.go
repository/products.go
routers/products.go

new func and new data dummy for product

new func for product list with image

---

controllers/profile.go
dtos/auth.go
routers/profile.go

fix backend: edit-delete-user

---

controllers/products.go
repository/products.go
routers/products.go

new feat backend for filter product

feat:backend filter product

---

controllers/products.go
routers/products.go

fix router in product

---

controllers/carts.go
controllers/transaction.go
dtos/transaction.go
models/transaction.go
models/transactionDetail.go
repository/carts.go
repository/transactionDetail.go
routers/carts.go

feat: fix payment flow

---

controllers/users.go
dtos/users.go
models/users.go
repository/users.go
routers/users.go

1. Add backend to insert user form and image

feat: add backend to insert user in admin page

---

controllers/profile.go
controllers/users.go
repository/profile.go
repository/users.go
routers/profile.go

1. add profile and user insert with image 
2. fix delete user and profile with image

feat: add and fix delete profile and user image

---

controllers/profile.go
dtos/profile.go
repository/profile.go
routers/profile.go

backend: edit user by admin
